# Generated by Django 5.1.2 on 2024-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Accountno', models.IntegerField(primary_key='accountno', serialize=False)),
                ('Aadharno', models.IntegerField()),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Branch', models.CharField(max_length=21)),
            ],
        ),
    ]
