# Generated by Django 5.1.2 on 2024-10-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='Branch',
            new_name='Bank',
        ),
    ]
